spring:
  application:
    name: windsurfer-weather-service
  threads:
    virtual:
      enabled: true

server:
  port: 8080

weatherbit:
  api:
    url: https://api.weatherbit.io/v2.0
    key: ${WEATHERBIT_API_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method